### PR TITLE
replace title with name in cost explorer fastmcp init

### PR DESCRIPTION
**Pull request by networkandcode**
Fixes

## Summary
TypeError: FastMCP.__init__() got an unexpected keyword argument 'title'
title seems work with 1.11.0 but not with 1.12.3

### Changes

> Please provide a summary of what's being changed
just the argument change, from title to name

### User experience

> Please share what the user experience looks like before and after this change

## Checklist

If your change doesn't seem to apply, please leave them unchecked.

* [x] I have reviewed the [contributing guidelines](https://github.com/awslabs/mcp/blob/main/CONTRIBUTING.md)
* [x] I have performed a self-review of this change
* [x] Changes have been tested
* [x] Changes are documented

Is this a breaking change? (Y/N)

**RFC issue number**:

Checklist:

* [ ] Migration process documented
* [ ] Implement warnings (if it can live side by side)

## Acknowledgment

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the [project license](https://github.com/awslabs/mcp/blob/main/LICENSE).

### CODE REVIEW

**Review by alexa-perlov — APPROVED** [review]

**Comment by atella-ai** [comment]
has this been released?

**Comment by ashchenn** [comment]
I've still run into this error using the latest version.

**Comment by atella-ai** [comment]
> I've still run into this error using the latest version.

same here
